version: '3'
services:
  db:
    image: mysql:8.0
    container_name: hackernameDB
    platform: linux/x86_64
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: hackernews
      MYSQL_ROOT_PASSWORD: dbpass
      MYSQL_USER: admin
      MYSQL_PASSWORD: dbpass
    ports:
      - "3307:3306"
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    # ホットリロードを使用するためairを叩くようコマンドを上書き
    command: air -c .air.toml
    depends_on:
      - db
    # コンテナ永続化
    tty: true
    stdin_open: true
    ports:
      - "5002:5002"
    # コンテナに持っていくファイルの指定
    volumes:
      - ./app:/go/src/app
      - ./.git:/go/src/.git
      - ./.gitignore:/go/src/.gitignore
      - ./.editorconfig:/go/src/.editorconfig
      - pkg:/go/pkg
volumes:
  pkg:
    driver: local
